### ISSUE TITLE
Redirect to Login

### ISSUE THREAD

**Issue by chuck-john** [auth0-samples/auth0-rubyonrails-sample#56]
Hello. We're attempting to redirect users to the auth0 login page without a button press. Is this what the [`redirect` route](https://github.com/auth0-samples/auth0-rubyonrails-sample/blob/master/sample/config/routes.rb#L8) is meant to accomplish? If so, the action seems to be left out of the [sample controller](https://github.com/auth0-samples/auth0-rubyonrails-sample/blob/master/sample/app/controllers/auth0_controller.rb).

A similar question was asked in #43, but it's still not clear how to capture the login URL manually.

**Comment by martijn** [comment]
Did you figure this out, by chance? The video tutorial linked in #43 is not very helpful since we're dealing with all the omniauth magic in Rails.

**Comment by martijn** [comment]
If you want to go through omniauth it seems you'd have to enable GET requests to the /auth/:provider route using the following code in an initializer:

```
OmniAuth.config.allowed_request_methods << :get
```

After that you can simply `redirect_to '/auth/auth0'`. Hoever, this is deemed undesirable because of CVE-2015-9284. It is recommended to only let the user access the sign in page explicitly (using a POST button/link).

**Comment by fsauter** [comment]
Took me a while to find this. The "redirect" route confused me too. Why is this in the example if there is no corresponding action for it?

It would be helpful to find your comment in the official tutorial (https://auth0.com/docs/quickstart/webapp/rails).

Thanks in any case :-)
